steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/esim-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/esim-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
    id: 'build-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/esim-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/esim-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/esim-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/esim-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'esim-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/esim-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8000'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'esim-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/esim-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '80'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://esim-backend-XXXXXXXXX.run.app/api'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

images:
  - 'gcr.io/$PROJECT_ID/esim-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/esim-backend:latest'
  - 'gcr.io/$PROJECT_ID/esim-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/esim-frontend:latest'

timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
