apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: esim-frontend
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: gcr.io/PROJECT_ID/esim-frontend:latest
          ports:
            - name: http1
              containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: 'https://esim-backend-XXXXXXXXX.run.app/api'
          resources:
            limits:
              cpu: '1000m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
  traffic:
    - percent: 100
      latestRevision: true
